version: "3.3"

services:
  webServer:
    image: nginx:alpine
    container_name: webserver
    ports:
      - "${APP_PORT}:80"
      - "${APP_SSL_PORT}:443"
    volumes:
      - ./docker/nginx/sites:/etc/nginx/conf.d
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/ssl:/etc/ssl
      - .:/var/www/html
    networks:
      - network

  php:
    build: docker/php
    container_name: php
    volumes:
      - .:/var/www/html
      - ./docker/php/conf/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - network

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "${APP_DB_PORT}:3306"
    volumes:
      - ./storage/database:/var/lib/mysql
    networks:
      - network
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

networks:
  network:
    driver: "bridge"

volumes:
  dbData:
    driver: "local"
